### ISSUE TITLE
Work around 25 user limit

### ISSUE THREAD

**Issue by JoshFoxBuckeye** [PagerDuty/pagerduty-bulk-user-mgr-sample#9]
This tool is great, I have been using it to pull down a CSV and convert it to a vCard. PagerDuty limits the number of users to 25 by default, 100 max. This is new I think because I don't recall this being an issue before. Could we please either get a workaround for this limit or some way to use the offset to get the next n users? Thanks!

**Comment by stmcallister** [comment]
@JoshFoxBuckeye Thanks for pointing this out! I've updated the code to get all the users in the account.

**Comment by stmcallister** [comment]
Going to close this issue. Please reopen if you continue to have problems.

**Comment by JoshFoxBuckeye** [comment]
This is perfect! Thank you so much!
